### ISSUE TITLE
Document stateful live PXE

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-docs#132]
Build on top of https://github.com/coreos/fedora-coreos-docs/pull/121 and document live PXE with `/var` on disk. (See also https://fedorapeople.org/~walters/devconfcz2020/fcos-live-pxe.html.)

**Comment by lucab** [comment]
I feel that these kinds of advanced scenarios with ad-hoc recipes would fit well into the "Tutorials" framework (https://github.com/coreos/fedora-coreos-docs/issues/106), what do you think?

**Comment by bgilbert** [comment]
We should document both the mechanics (Butane config) and the philosophy.  The Ignition config runs on every boot, and should be written to avoid wiping existing partition tables, LUKS volumes, and filesystems.  Instead, the config should specify these structures so that they're created on the first boot and preserved on subsequent boots.

Configs should also avoid appending to files in persistent storage.
