### ISSUE TITLE
Improved RAID documentation

### ISSUE THREAD

**Issue by kanadaj** [coreos/fedora-coreos-docs#232]
**Describe the enhancement**
I'm trying to set up nodes with a pair of drives so that / and /var are on separate raid partitions on the same pair of drives, but there is a serious lack of documentation around RAID setups. 

**System details**
 - Bare Metal
 - Fedora CoreOS version

**Additional information**
I've tried to either create a full-disk raid array and then partition that (which doesn't seem to work - I'm guessing partitioning has to run first?) and partitioning the disks with 2 partitions (first starts at 5000 with a size_mib of 100k, the second starts at 0 and size of 0) and then turn those into arrays but it seems to crash the system during ignition either way.

Some working examples or explicitly saying if it's not supported would be welcome.

**Comment by bgilbert** [comment]
Note that RAIDing the root filesystem isn't sufficient for a successful boot after a drive failure, because there's also `/boot`, the ESP (if on UEFI), and the bootloader (if on BIOS).  The current FCOS `testing` release supports full-disk RAID via the FCC `boot_device.mirror` section; see [here](https://coreos.github.io/fcct/examples/#mirrored-boot-disk).  The second example is close to what you're looking for.

This functionality will not be available in FCOS `stable` until the next release.  We plan to add more FCOS documentation soon.
